services:
  - type: web
    name: beastmode-backend
    env: node
    plan: free # O usa 'starter', 'standard', etc. según tu necesidad
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: beastmode-db
          property: connectionString
      - key: JWT_SECRET
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false