
import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/Components/Footer/Footer";
import AuthProvider from "./AuthProvider";
import LoginFormProvider from "@/Components/loginouth/LoginProvider";
import StripeProvider from "@/Components/Suscripcion/page";
import { SessionUserProvider } from "./SessionUserContext";
import { Suspense } from "react";
import { Toaster } from "react-hot-toast";
import Navbarp from "@/Components/Navbarp/Navbar";
import DomainUpdater from "@/utils/domainUpdater"; 

export const metadata: Metadata = {
  title: "BeastMode",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen pt-24">
        <AuthProvider>
          <SessionUserProvider>
            <StripeProvider>
              <Navbarp />
              <Toaster position="top-center" />
                {/* {<LoginFormProvider />} */}
              <DomainUpdater /> 
              <Suspense fallback={<div>Cargando....</div>}>{children}</Suspense>
              <Footer />
            </StripeProvider>
          </SessionUserProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
